### ISSUE TITLE
UnHandled Exception

### ISSUE THREAD

**Issue by madhabnath** [GennadiiSvichinskyi/test-grpc-dapr#1]
While Running Client, getting the below issue -

Updating metadata for app command: dotnet run testGrpcDaprService SayHello GrpcLover
You're up and running! Both Dapr and your app logs will appear here.

== APP == Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=Unimplemented, Detail="unknown service dapr.proto.dapr.v1.Dapr")

== APP ==    at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, CancellationToken cancellationToken)

== APP ==    at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsync(String appId, String methodName, Any data, HTTPExtension httpExtension, CancellationToken cancellationToken)

== APP ==    at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TRequest,TResponse](String appId, String methodName, TRequest data, HTTPExtension httpExtension, CancellationToken cancellationToken)

== APP ==    at TestGrpcWithDapr.Client.Program.Main(String[] args) in \SimpleDaprGrpc-master\TestGrpcWithDapr.Client\Program.cs:line 21

== APP ==    at TestGrpcWithDapr.Client.Program.<Main>(String[] args)

**Comment by GennadiiSvichinskyi** [comment]
@madhabnath , thanks for reporting this issue. I've updated all references to the latest DAPR runtime and now it should be Okay. Let me know if it helps.

**Comment by madhabnath** [comment]
Thanks @GennadiiSvichinskyi. It's working absolutely fine now. It would be better for the community like me who is novice in the area, if you provide any documentation about your implementation at later stage.
